name: Auto Merge

on:
  pull_request_target:

jobs:
  merge-me:
    name: Auto Merge
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Auto Merge
        uses: ridedott/merge-me-action@v2.9.27
        with:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          PRESET: DEPENDABOT_MINOR